#!/usr/bin/env bash
# =====================================================================
#  One-click LoRA fine-tune + evaluation pipeline for DINOv3 (HF / ViT-B)
#
#  Pipeline:
#    [1] Install Python deps (transformers, safetensors)
#    [2] Zero-shot feature extraction + MNN matching       (baseline)
#    [3] Zero-shot evaluation                              (baseline metrics)
#    [4] LoRA fine-tune                                    (training)
#    [5] Fine-tuned feature extraction + MNN matching      (latest ckpt)
#    [6] Fine-tuned evaluation                             (latest-ckpt metrics)
#    [7] Per-epoch evaluation                              (curve over training)
#
#  All produced metrics live under `output/<dataset>_<model>/`,
#  drop-in compatible with the existing zero-shot folders.
#
#  Usage:
#    bash scripts/train_oneclick.sh                          # default = navi, small
#    bash scripts/train_oneclick.sh navi
#    MODEL=middle bash scripts/train_oneclick.sh navi
#    MODEL=small  bash scripts/train_oneclick.sh navi 5      # only run 5 epochs
#
#  Skip earlier steps (resume the pipeline mid-way):
#    START_STEP=4 bash scripts/train_oneclick.sh navi          # start from training
#    START_STEP=5 bash scripts/train_oneclick.sh navi          # skip train, eval latest ckpt
#    START_STEP=7 bash scripts/train_oneclick.sh navi          # only per-epoch eval
#    START_STEP=4 END_STEP=4 bash scripts/train_oneclick.sh navi   # train only
#
#  Per-epoch eval resume controls (STEP 7):
#    EVAL_START_EPOCH=5 START_STEP=7 bash scripts/train_oneclick.sh navi
#        → only eval epoch005, epoch006, ... (skip 0..4)
#    EVAL_EVERY=3 START_STEP=7 bash scripts/train_oneclick.sh navi
#        → only eval every 3rd epoch: 0, 3, 6, 9, 12, ...
#    EVAL_EVERY=3 EVAL_START_EPOCH=9 START_STEP=7 bash scripts/train_oneclick.sh navi
#        → only eval epochs 9, 12, 15, ... (combine stride + start)
#    EVAL_FORCE=1 START_STEP=7 bash scripts/train_oneclick.sh navi
#        → re-evaluate every epoch even if results already exist
#    (default behaviour: skip any epoch whose evaluation_results.txt exists)
# =====================================================================
set -euo pipefail

DATASET=${1:-navi}
EPOCHS=${2:-15}

# Model size: 'small' (≈ 86M, ViT-S/B) or 'middle' (≈ 300M, ViT-L). Default = small.
MODEL=${MODEL:-small}
case "$MODEL" in
  small|middle) ;;
  *)
    echo "Unknown MODEL '$MODEL'. Choose: small | middle"
    exit 1
    ;;
esac

# Step gating: which steps to run. Default = full pipeline (1..7).
# Override via env: START_STEP=4 (skip 1..3), END_STEP=6 (skip 7), etc.
START_STEP=${START_STEP:-1}
END_STEP=${END_STEP:-7}

# Per-epoch eval (STEP 7) resume controls.
EVAL_START_EPOCH=${EVAL_START_EPOCH:-0}     # numeric, e.g. 0, 5, 12
EVAL_EVERY=${EVAL_EVERY:-1}                 # stride: only eval epoch where idx % EVAL_EVERY == 0
EVAL_FORCE=${EVAL_FORCE:-0}                 # 1 = re-run even if results exist

# Helper: returns 0 (success) if step $1 should be executed.
run_step() {
    local s=$1
    [ "$s" -ge "$START_STEP" ] && [ "$s" -le "$END_STEP" ]
}

# In tiny mode we override epochs to a small value if user didn't pass one.
if [ "$DATASET" = "tiny" ] && [ -z "${2:-}" ]; then
    EPOCHS=2
fi

# ---------------------------------------------------------------------
#  Paths (edit only if your layout differs)
# ---------------------------------------------------------------------
PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$PROJECT_ROOT"

# Each model size lives in its own sub-directory of dinov3_weights/.
#   dinov3_weights/dinov3-small/   (≈ 86M  ViT-S/B)
#   dinov3_weights/dinov3-middle/  (≈ 300M ViT-L, 1.21 GB safetensors)
WEIGHTS_DIR="dinov3_weights/dinov3-${MODEL}"
if [ ! -d "$WEIGHTS_DIR" ]; then
    echo "[error] Weights directory not found: $WEIGHTS_DIR"
    echo "        Expected layout:"
    echo "          dinov3_weights/dinov3-small/   (HF safetensors)"
    echo "          dinov3_weights/dinov3-middle/  (HF safetensors)"
    exit 1
fi

IMG_SIZE=448
BATCH_SIZE=8
LR=1e-4
LORA_RANK=4
LORA_ALPHA=8.0

# Per-dataset settings
case "$DATASET" in
  tiny)
    # Synthetic pipeline-smoke dataset. Auto-generated below.
    TRAIN_PAIRS="datasets/tiny/pairs.txt"
    EVAL_PAIRS="datasets/tiny/pairs.txt"
    DATA_ROOT="datasets/tiny"
    DEPTH_ROOT=""
    IMG_SIZE=480
    EVAL_W=480
    EVAL_H=480
    ;;
  navi)
    TRAIN_PAIRS="finetune/navi_train_pairs.txt"
    # Evaluation pairs priority:
    #   1. datasets/navi_test_pairs.txt  ← generated by scripts/build_navi_pairs.sh
    #                                       (image-disjoint from training set)
    #   2. datasets/navi_with_gt.txt     ← legacy lmz-provided file (if available)
    #   3. finetune/navi_train_pairs.txt ← last-resort fallback (NOT recommended:
    #                                       overlaps with training images)
    if [ -f "datasets/navi_test_pairs.txt" ]; then
        EVAL_PAIRS="datasets/navi_test_pairs.txt"
    elif [ -f "datasets/navi_with_gt.txt" ]; then
        EVAL_PAIRS="datasets/navi_with_gt.txt"
    else
        EVAL_PAIRS="finetune/navi_train_pairs.txt"
        echo "[warn] No held-out test pairs found; falling back to training pairs."
        echo "[warn] Run 'bash scripts/build_navi_pairs.sh' first for a clean eval."
    fi
    DATA_ROOT="datasets/navi_v1.5"
    DEPTH_ROOT=""
    EVAL_W=1024
    EVAL_H=1024
    ;;
  navi_mini)
    TRAIN_PAIRS="finetune/navi_train_pairs_mini.txt"
    if [ -f "datasets/navi_test_pairs.txt" ]; then
        EVAL_PAIRS="datasets/navi_test_pairs.txt"
    elif [ -f "datasets/navi_with_gt.txt" ]; then
        EVAL_PAIRS="datasets/navi_with_gt.txt"
    else
        EVAL_PAIRS="finetune/navi_train_pairs_mini.txt"
        echo "[warn] No held-out test pairs found; falling back to training pairs."
    fi
    DATA_ROOT="datasets/navi_v1.5"
    DEPTH_ROOT=""
    EVAL_W=1024
    EVAL_H=1024
    ;;
  scannet)
    TRAIN_PAIRS="finetune/scannet_train_mini.txt"
    EVAL_PAIRS="datasets/scannet_with_gt.txt"
    DATA_ROOT="datasets/scannet"
    DEPTH_ROOT="datasets/scannet"
    EVAL_W=640
    EVAL_H=480
    ;;
  *)
    echo "Unknown DATASET '$DATASET'. Choose: tiny | navi | navi_mini | scannet"
    exit 1
    ;;
esac

# ---------------------------------------------------------------------
#  Output layout (all run artefacts live under output/<dataset>_<model>/)
#
#    output/<dataset>_<model>/
#      ├── lora_ckpt/        ← LoRA checkpoints + training log
#      ├── mnn_zeroshot/     ← zero-shot feature matches (CSV)
#      ├── mnn_finetuned/    ← fine-tuned feature matches (CSV)
#      ├── eval_zeroshot/    ← zero-shot evaluation results
#      └── eval_finetuned/   ← fine-tuned evaluation results
# ---------------------------------------------------------------------
OUT_ROOT="output/${DATASET}_${MODEL}"
OUT_LORA="${OUT_ROOT}/lora_ckpt"
MNN_ZS="${OUT_ROOT}/mnn_zeroshot"
MNN_FT="${OUT_ROOT}/mnn_finetuned"
EVAL_ZS="${OUT_ROOT}/eval_zeroshot"
EVAL_FT="${OUT_ROOT}/eval_finetuned"
EVAL_PER_EPOCH="${OUT_ROOT}/eval_per_epoch"
mkdir -p "$OUT_ROOT"

echo "===================================================================="
echo "  DINOv3 LoRA-HF one-click pipeline"
echo "  Dataset      : $DATASET"
echo "  Model        : $MODEL  ($WEIGHTS_DIR)"
echo "  Train pairs  : $TRAIN_PAIRS"
echo "  Eval pairs   : $EVAL_PAIRS"
echo "  Data root    : $DATA_ROOT"
echo "  Output root  : $OUT_ROOT"
echo "  Epochs       : $EPOCHS"
echo "  Img size     : $IMG_SIZE"
echo "  LoRA rank    : $LORA_RANK"
echo "  Steps        : ${START_STEP}..${END_STEP}"
if [ "$START_STEP" -le 7 ] && [ "$END_STEP" -ge 7 ]; then
echo "  Eval resume  : start_epoch=$EVAL_START_EPOCH  every=$EVAL_EVERY  force=$EVAL_FORCE"
fi
echo "===================================================================="

# ---------------------------------------------------------------------
#  Auto-activate project-local .venv (built by scripts/setup_env.sh)
# ---------------------------------------------------------------------
VENV_DIR="$PROJECT_ROOT/.venv"
if [ -d "$VENV_DIR" ]; then
    # shellcheck source=/dev/null
    source "$VENV_DIR/bin/activate"
    echo "[env] Activated venv: $VENV_DIR"
elif command -v python >/dev/null 2>&1 || command -v python3 >/dev/null 2>&1; then
    echo "[env] No local .venv found at $VENV_DIR."
    echo "      Recommended: bash scripts/setup_env.sh"
    echo "      Falling back to system Python — packages may be missing."
fi
PY=$(command -v python || command -v python3)
echo "[env] Python: $($PY --version 2>&1) ($PY)"

# ---------------------------------------------------------------------
#  Step 1 — verify deps (do NOT silently install; user runs setup_env.sh)
# ---------------------------------------------------------------------
if run_step 1; then
echo ""
echo "[1/7] Verifying Python deps..."
$PY - <<'PY'
import importlib, sys
need = ["torch", "torchvision", "transformers", "safetensors",
        "numpy", "cv2", "PIL"]
missing = []
for m in need:
    try:
        mod = importlib.import_module(m)
        v = getattr(mod, "__version__", "?")
        print(f"  ok  {m:14s} {v}")
    except Exception as e:
        missing.append(m)
        print(f"  MISS {m:14s} ({e.__class__.__name__})")
if missing:
    print(f"\nMissing modules: {missing}")
    print("Run: bash scripts/setup_env.sh")
    sys.exit(1)
PY
else
    echo ""
    echo "[1/7] SKIPPED (START_STEP=$START_STEP)"
fi

# ---------------------------------------------------------------------
#  Step 1.5 — auto-generate tiny synthetic dataset if needed
# ---------------------------------------------------------------------
if [ "$DATASET" = "tiny" ]; then
    if [ ! -f "$TRAIN_PAIRS" ]; then
        echo ""
        echo "[1.5] Generating tiny synthetic dataset → $DATA_ROOT/"
        $PY scripts/make_tiny_dataset.py \
            --out "$DATA_ROOT" \
            --num_pairs 8 \
            --img_size "$IMG_SIZE"
    else
        echo "[1.5] Reusing existing tiny dataset at $DATA_ROOT/"
    fi
fi

# ---------------------------------------------------------------------
#  Step 2 — zero-shot extraction + MNN matching
# ---------------------------------------------------------------------
if run_step 2; then
echo ""
echo "[2/7] Zero-shot feature extraction + MNN matching → $MNN_ZS"
$PY -m finetune.extract_and_match_hf \
    --weights_dir "$WEIGHTS_DIR" \
    --pairs "$EVAL_PAIRS" \
    --data_root "$DATA_ROOT" \
    --output_dir "$MNN_ZS" \
    --img_size "$IMG_SIZE" \
    --eval_resize "$EVAL_W" "$EVAL_H"
else
    echo ""
    echo "[2/7] SKIPPED"
fi

# ---------------------------------------------------------------------
#  Step 3 — zero-shot evaluation
# ---------------------------------------------------------------------
if run_step 3; then
echo ""
echo "[3/7] Zero-shot evaluation → $EVAL_ZS"
mkdir -p "$EVAL_ZS"
$PY evaluate/evaluate_csv_essential.py \
    --input_pairs "$EVAL_PAIRS" \
    --input_dir "$DATA_ROOT" \
    --input_csv_dir "$MNN_ZS" \
    --output_dir "$EVAL_ZS" \
    --resize "$EVAL_W" "$EVAL_H" || \
    echo "  (evaluate script returned non-zero — inspect $EVAL_ZS)"
else
    echo ""
    echo "[3/7] SKIPPED"
fi

# ---------------------------------------------------------------------
#  Step 4 — LoRA fine-tune
# ---------------------------------------------------------------------
if run_step 4; then
echo ""
echo "[4/7] LoRA fine-tuning → $OUT_LORA"
$PY -m finetune.train_lora_hf \
    --weights_dir "$WEIGHTS_DIR" \
    --train_pairs "$TRAIN_PAIRS" \
    --data_root "$DATA_ROOT" \
    --depth_root "$DEPTH_ROOT" \
    --output_dir "$OUT_LORA" \
    --epochs "$EPOCHS" \
    --batch_size "$BATCH_SIZE" \
    --lr "$LR" \
    --img_size "$IMG_SIZE" \
    --lora_rank "$LORA_RANK" \
    --lora_alpha "$LORA_ALPHA"
else
    echo ""
    echo "[4/7] SKIPPED"
fi

CKPT="$OUT_LORA/checkpoint_latest.pth"

# ---------------------------------------------------------------------
#  Step 5 — fine-tuned extraction + MNN matching
# ---------------------------------------------------------------------
if run_step 5; then
echo ""
echo "[5/7] Fine-tuned feature extraction (latest ckpt) → $MNN_FT"
if [ ! -f "$CKPT" ]; then
    echo "  [error] checkpoint not found: $CKPT"
    echo "          Run step 4 first, or check $OUT_LORA"
    exit 1
fi
$PY -m finetune.extract_and_match_hf \
    --weights_dir "$WEIGHTS_DIR" \
    --checkpoint "$CKPT" \
    --lora_rank "$LORA_RANK" \
    --lora_alpha "$LORA_ALPHA" \
    --pairs "$EVAL_PAIRS" \
    --data_root "$DATA_ROOT" \
    --output_dir "$MNN_FT" \
    --img_size "$IMG_SIZE" \
    --eval_resize "$EVAL_W" "$EVAL_H"
else
    echo ""
    echo "[5/7] SKIPPED"
fi

# ---------------------------------------------------------------------
#  Step 6 — fine-tuned evaluation (using checkpoint_latest.pth)
# ---------------------------------------------------------------------
if run_step 6; then
echo ""
echo "[6/7] Fine-tuned evaluation (latest ckpt) → $EVAL_FT"
mkdir -p "$EVAL_FT"
$PY evaluate/evaluate_csv_essential.py \
    --input_pairs "$EVAL_PAIRS" \
    --input_dir "$DATA_ROOT" \
    --input_csv_dir "$MNN_FT" \
    --output_dir "$EVAL_FT" \
    --resize "$EVAL_W" "$EVAL_H" || \
    echo "  (evaluate script returned non-zero — inspect $EVAL_FT)"
else
    echo ""
    echo "[6/7] SKIPPED"
fi

# ---------------------------------------------------------------------
#  Step 7 — per-epoch evaluation
#
#  Iterate over every checkpoint_epoch*.pth produced during training,
#  run extract+evaluate for each, then summarise into a single table:
#
#    output/<dataset>_<model>/eval_per_epoch/
#      ├── epoch000/                 ← extract MNN csvs
#      │   └── eval/                 ← evaluation_results.txt
#      ├── epoch001/...
#      └── summary.tsv               ← one row per epoch (key metrics)
#
#  Resume behaviour:
#    * EVAL_START_EPOCH=N skips checkpoints whose epoch index < N.
#    * Without EVAL_FORCE=1, any epoch whose `eval/evaluation_results.txt`
#      already exists is skipped (so an interrupted run can be continued
#      simply by re-invoking with START_STEP=7 — completed epochs are
#      reused, and remaining epochs are processed).
# ---------------------------------------------------------------------
SUMMARY_TSV="$EVAL_PER_EPOCH/summary.tsv"
if run_step 7; then
echo ""
echo "[7/7] Per-epoch evaluation → $EVAL_PER_EPOCH"
echo "      EVAL_START_EPOCH=$EVAL_START_EPOCH  EVAL_EVERY=$EVAL_EVERY  EVAL_FORCE=$EVAL_FORCE"
mkdir -p "$EVAL_PER_EPOCH"

# Only (re)write the TSV header when starting from scratch; otherwise
# we'll regenerate the file at the very end from per-epoch results.
if [ ! -f "$SUMMARY_TSV" ]; then
    echo -e "epoch\tauc@5\tauc@10\tauc@20\tprecision\trecall" > "$SUMMARY_TSV"
fi

shopt -s nullglob
CKPT_LIST=( "$OUT_LORA"/checkpoint_epoch*.pth )
shopt -u nullglob

if [ ${#CKPT_LIST[@]} -eq 0 ]; then
    echo "  [warn] No checkpoint_epoch*.pth found in $OUT_LORA — skipping per-epoch eval."
else
    echo "  Found ${#CKPT_LIST[@]} epoch checkpoints."
    for CKPT_E in "${CKPT_LIST[@]}"; do
        # Extract the 3-digit epoch number from filename: checkpoint_epoch007.pth → 007
        FNAME=$(basename "$CKPT_E")
        EPOCH_TAG="${FNAME#checkpoint_epoch}"
        EPOCH_TAG="${EPOCH_TAG%.pth}"
        # Strip leading zeros for numeric comparison (10#NNN forces base-10 parsing).
        EPOCH_NUM=$((10#$EPOCH_TAG))
        EP_DIR="$EVAL_PER_EPOCH/epoch${EPOCH_TAG}"
        EP_EVAL_DIR="$EP_DIR/eval"
        RES="$EP_EVAL_DIR/evaluation_results.txt"

        # ── Resume gate 1: skip epochs below the requested start. ──
        if [ "$EPOCH_NUM" -lt "$EVAL_START_EPOCH" ]; then
            echo ""
            echo "  ── epoch ${EPOCH_TAG} ── SKIP (< EVAL_START_EPOCH=$EVAL_START_EPOCH)"
            continue
        fi

        # ── Resume gate 2: stride filter (every N epochs). ──
        if [ "$EVAL_EVERY" -gt 1 ] && [ $((EPOCH_NUM % EVAL_EVERY)) -ne 0 ]; then
            echo ""
            echo "  ── epoch ${EPOCH_TAG} ── SKIP (stride: idx % $EVAL_EVERY != 0)"
            continue
        fi

        # ── Resume gate 3: skip already-finished epochs (unless forced). ──
        if [ -f "$RES" ] && [ "$EVAL_FORCE" != "1" ]; then
            echo ""
            echo "  ── epoch ${EPOCH_TAG} ── SKIP (already evaluated: $RES)"
            continue
        fi

        mkdir -p "$EP_EVAL_DIR"

        echo ""
        echo "  ── epoch ${EPOCH_TAG} ──────────────────────────────"
        echo "  ckpt : $CKPT_E"
        echo "  out  : $EP_DIR"

        # 7a. extract + MNN match for this epoch
        $PY -m finetune.extract_and_match_hf \
            --weights_dir "$WEIGHTS_DIR" \
            --checkpoint "$CKPT_E" \
            --lora_rank "$LORA_RANK" \
            --lora_alpha "$LORA_ALPHA" \
            --pairs "$EVAL_PAIRS" \
            --data_root "$DATA_ROOT" \
            --output_dir "$EP_DIR" \
            --img_size "$IMG_SIZE" \
            --eval_resize "$EVAL_W" "$EVAL_H" || {
                echo "  [warn] extract failed for epoch ${EPOCH_TAG}, skipping eval."
                continue
            }

        # 7b. evaluate
        $PY evaluate/evaluate_csv_essential.py \
            --input_pairs "$EVAL_PAIRS" \
            --input_dir "$DATA_ROOT" \
            --input_csv_dir "$EP_DIR" \
            --output_dir "$EP_EVAL_DIR" \
            --resize "$EVAL_W" "$EVAL_H" || {
                echo "  [warn] evaluate returned non-zero for epoch ${EPOCH_TAG}"
            }
    done

    # ──────────────────────────────────────────────────────────────
    # Rebuild summary.tsv from every existing per-epoch result file,
    # so the table is consistent regardless of resume / force behaviour.
    # ──────────────────────────────────────────────────────────────
    echo ""
    echo "  Rebuilding summary.tsv from existing per-epoch results..."
    echo -e "epoch\tauc@5\tauc@10\tauc@20\tprecision\trecall" > "$SUMMARY_TSV"
    shopt -s nullglob
    for EP_RES in "$EVAL_PER_EPOCH"/epoch*/eval/evaluation_results.txt; do
        EP_TAG=$(basename "$(dirname "$(dirname "$EP_RES")")")
        EP_TAG="${EP_TAG#epoch}"
        $PY - "$EP_RES" "$EP_TAG" "$SUMMARY_TSV" <<'PY'
import re, sys
res_path, epoch_tag, summary_path = sys.argv[1:4]
text = open(res_path, "r", errors="ignore").read()

def grab(pattern, default="-"):
    m = re.search(pattern, text, re.IGNORECASE)
    return m.group(1) if m else default

auc5  = grab(r"AUC@5[^0-9\-]*([0-9.]+)")
auc10 = grab(r"AUC@10[^0-9\-]*([0-9.]+)")
auc20 = grab(r"AUC@20[^0-9\-]*([0-9.]+)")
prec  = grab(r"Precision[^0-9\-]*([0-9.]+)")
rec   = grab(r"Recall[^0-9\-]*([0-9.]+)")

with open(summary_path, "a") as f:
    f.write(f"{epoch_tag}\t{auc5}\t{auc10}\t{auc20}\t{prec}\t{rec}\n")
PY
    done
    shopt -u nullglob

    echo ""
    echo "  Per-epoch summary written to: $SUMMARY_TSV"
    echo "  ──────── summary preview ────────"
    column -t -s $'\t' "$SUMMARY_TSV" || cat "$SUMMARY_TSV"
fi
else
    echo ""
    echo "[7/7] SKIPPED"
fi

echo ""
echo "===================================================================="
echo "  DONE."
echo "  Zero-shot results : $EVAL_ZS/evaluation_results.txt"
echo "  Fine-tuned results: $EVAL_FT/evaluation_results.txt"
echo "  Per-epoch summary : $SUMMARY_TSV"
echo "===================================================================="
